# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aprendiendo con Mayúsculas' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!

  # Pods for Aprendiendo con Mayúsculas
  pod 'SimpleRoulette', '~> 0.2'

end
